name: 🐞 Bug report
description: Report a reproducible bug
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the information below.

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug clearly and concisely.
      placeholder: Tell us what you expected to happen and what actually happened.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      placeholder: e.g. 1.2.3
