name: ✨ Feature request
description: Suggest an idea or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: What problem does this solve?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed solution
      placeholder: Describe your idea for a solution to the problem.
